### ISSUE TITLE
About solenoid

### ISSUE THREAD

**Issue by F1hone** [dcpedit/redherring#1]
Hello,
It's a really interesting keyboard, it's a really nice piece of work, I'm especially interested in his solenoids, "da da da", sounds great, but the best I can find on my local shopping site The parameters of the solenoid valve are DC3V 0.5A; DC5V (0.83A, 0.41A), I want to know which one should I choose, I am looking forward to your answer, thank you

**Comment by dcpedit** [comment]
I would go with the 3v one just to be safe. The 5v one might work depending on how much power your other components are drawing. Hard to predict without actually trying it out.

**Comment by F1hone** [comment]
Thank you very much for your answer, 
I will give it a try and I will come back and let you know when I get the results

**Comment by jhc2414169248** [comment]
> 
Hi, did you try successfully? Solenoid with 5V working?

**Comment by dcpedit** [comment]
I was not able to get a 5V solenoid working.  Only a 4.5V worked for me, so I would not go higher than that.

**Comment by F1hone** [comment]
Sorry, I'm not allowed to receive courier due to the novel coronavirus epidemic in my area, so I haven't tried it yet, but I think 3v should work

**Comment by dcpedit** [comment]
I've received confirmation that a 3v solenoid works.
