### ISSUE TITLE
redherring_vial.hex (solenoid support) source files

### ISSUE THREAD

**Issue by baconspoon85** [dcpedit/redherring#4]
Would it be possible for you to commit the source files for redherring_vial.hex? The one with solenoid support that you most recently committed in this repository? I would like to edit the keymap to support tap-mod shift keys on the spacebars, but vial doesn't support that function, so I’d have to compile new firmware. I found some files you posted at https://github.com/dcpedit/vial-qmk/tree/dcpedit/keyboards/dcpedit/redherring, but I suspect those don’t correspond to the published hex. I recompiled it to test this theory by cloning the found files to qmk_firmware/keyboards/redherring and running 'make redherring:vial' in QMK MSYS. I was able to compile a new hex and flash it to the board, but there are three distinct differences in function:

1. OLED font and logo are no longer displaying (I just get garbled noise).
2. Rotary encoder won't control volume or page up/down as expected.
3. Vial no longer recognizes the keyboard.

Everything else works fine but I'm hoping with the right source files I can avoid loosing those functions.

**Comment by baconspoon85** [comment]
Never mind. I just realized the tap-hold keycodes are in the Quantum tab and QMK Settings has Tapping Term under the Tap-Hold tab. Would still be cool to be able to update the firmware directly though. I'd like to try getting a track nub to work on one of these.

**Comment by dcpedit** [comment]
The source files can't be copied over into QMK because it was built using the Vial source code.  You'll need to clone my entire repo and build from there.  Here are the Vial docs for reference: https://get.vial.today/docs/
