### ISSUE TITLE
Very good design, is there a sample for reference?

### ISSUE THREAD

**Issue by 906051999** [dcpedit/redherring#5]
This is an eye-opening design, thanks to the author's dedication and selfless dedication.
I'm a keyboard lover, but just a beginner.
May I ask if there is a finished product to refer to, or better yet, I can just buy a sample, which may sound a bit low-level, lol.

**Comment by Galvo87** [comment]
Hi, if you're interested I'm building some, a bit modified to my taste regarding the aesthetic :)

**Comment by 906051999** [comment]
It sounds very exciting. I look forward to your work. 
If it is convenient, you can leave a channel and I can go and have a look.

**Comment by Galvo87** [comment]
Sure, I will take some photos when finished [on my IG](https://www.instagram.com/lg_galvo/)
