### ISSUE TITLE
OLED BOM header part verification request

### ISSUE THREAD

**Issue by JellyTitan** [dcpedit/redherring#6]
The 4 pin OLED header link in the bom points to a part that looks different than the part used in the build guide. 
Does the BOM link point to the correct part? If not, can you point me to the correct part? 
[Mouse part](https://www.mouser.com/ProductDetail/517-929850-01-04-RA)
[Build guide image](https://user-images.githubusercontent.com/800930/144702052-e8cfc8cd-1268-4091-b99a-a7bb67b7605b.jpg)

**Comment by baconspoon85** [comment]
That's a stock image on the Mouser site. They do that a lot to represent a family of product rather than put an image for each iteration. If you read the description, it's for single row, 4-position connector like it should be.

**Comment by JellyTitan** [comment]
Thank you! I appreciate your patience - I learned something new.
