### ISSUE TITLE
Can you recommend an alternate 10k resistor?

### ISSUE THREAD

**Issue by JellyTitan** [dcpedit/redherring#7]
10k resistor in BOM has long lead times at both Mouser and digi-key. Can you recommend an alternative? 
[BOM 10k resistor](https://www.mouser.com/ProductDetail/603-MFR-12FTF52-10K)
I _think_ this might be a viable replacement, but I'm not sure about the whole carbon vs metal and the different % bit.
[Possible alternative](https://www.mouser.com/ProductDetail/YAGEO/CFR-12JT-52-10K?qs=sGAEpiMZZMukHu%252BjC5l7YYQbpz0rXRQCHY0h6eFAuV0%3D)

**Comment by dcpedit** [comment]
Yes, that alternative should work fine

**Comment by JellyTitan** [comment]
Thanks! I appreciate the quick response  - I'll submit a PR with an alternative link.
