### ISSUE TITLE
Hotswap support for Mill-Max socket

### ISSUE THREAD

**Issue by saikocat** [dcpedit/redherring#9]
It seems like the current PCB mounting hole diameter is only 1.47mm, which I think make it near impossible to insert the Mill-Max hotswap socket due to the same thickness without accounting for drilling tolerance/error.

Like for example the 0305 has the follow specs:
* Diameter: 1.47 mm
* Recommended PCB mounting hole diameter: 1.50-1.55 mm
* Flange thickness: 0.64 mm
* Flange diameter: 1.93 mm

EDIT: Is the reason due to the switch being raised higher (than sitting flushed) causing issue with the acrylic layers?

Is there any plan to support this? Or strictly pure soldered board only? Thanks!

**Comment by dcpedit** [comment]
The current design actually does support mill-max sockets.  I've built a
few boards with them and sockets drop right into the hole with no issue.
As you can see in this photo, the bottom pcb has the sockets installed:
https://imgur.com/8ku5P5I

**Comment by saikocat** [comment]
Thank you for the reply. I've experienced that 1.5mm to be snug-fit, in rare cases failure to push through. I guess this is highly depending on the PCB manufacturer tolerance.

The specs https://www.mill-max.com/products/receptacle/0305 also suggests the mounting hole to a bit larger (though its diameter is exactly the same as your footprint hole at 1.47mm).

This could be a confirmation bias thing from our experiences. But if it works for majority of the people building the board then we can just close this issue.

**Comment by JellyTitan** [comment]
The 0305's worked for me on boards made by jlcpcb. Perhaps these should be added to BOM as optional? Please don't make me count the holes . . .

**Comment by dcpedit** [comment]
PR #11 which adds hotswap sockets to the PCB has been merged.
